
INSERT INTO Countries(name) VALUES('Afghánistán');
INSERT INTO Countries(name) VALUES('Albánie');
INSERT INTO Countries(name) VALUES('Alžírsko');
INSERT INTO Countries(name) VALUES('Andorra');
INSERT INTO Countries(name) VALUES('Angola');
INSERT INTO Countries(name) VALUES('Antigua a Barbuda');
INSERT INTO Countries(name) VALUES('Argentina');
INSERT INTO Countries(name) VALUES('Arménie');
INSERT INTO Countries(name) VALUES('Austrálie');
INSERT INTO Countries(name) VALUES('Rakousko');
INSERT INTO Countries(name) VALUES('Ázerbájdžán');
INSERT INTO Countries(name) VALUES('Bahamy');
INSERT INTO Countries(name) VALUES('Bahrajn');
INSERT INTO Countries(name) VALUES('Bangladéš');
INSERT INTO Countries(name) VALUES('Barbados');
INSERT INTO Countries(name) VALUES('Bělorusko');
INSERT INTO Countries(name) VALUES('Belgie');
INSERT INTO Countries(name) VALUES('Belize');
INSERT INTO Countries(name) VALUES('Benin');
INSERT INTO Countries(name) VALUES('Bhútán');
INSERT INTO Countries(name) VALUES('Bolívie');
INSERT INTO Countries(name) VALUES('Bosna a Hercegovina');
INSERT INTO Countries(name) VALUES('Botswana');
INSERT INTO Countries(name) VALUES('Brazílie');
INSERT INTO Countries(name) VALUES('Brunej');
INSERT INTO Countries(name) VALUES('Bulharsko');
INSERT INTO Countries(name) VALUES('Burkina Faso');
INSERT INTO Countries(name) VALUES('Burundi');
INSERT INTO Countries(name) VALUES('Kambodža');
INSERT INTO Countries(name) VALUES('Kamerun');
INSERT INTO Countries(name) VALUES('Kanada');
INSERT INTO Countries(name) VALUES('Kapverdy');
INSERT INTO Countries(name) VALUES('Středoafrická republika');
INSERT INTO Countries(name) VALUES('Čad');
INSERT INTO Countries(name) VALUES('Chile');
INSERT INTO Countries(name) VALUES('Čína');
INSERT INTO Countries(name) VALUES('Kolumbie');
INSERT INTO Countries(name) VALUES('Komory');
INSERT INTO Countries(name) VALUES('Kongo (Brazzaville)');
INSERT INTO Countries(name) VALUES('Kongo (Kinshasa)');
INSERT INTO Countries(name) VALUES('Kostarika');
INSERT INTO Countries(name) VALUES('Chorvatsko');
INSERT INTO Countries(name) VALUES('Kuba');
INSERT INTO Countries(name) VALUES('Kypr');
INSERT INTO Countries(name) VALUES('Česko');
INSERT INTO Countries(name) VALUES('Dánsko');
INSERT INTO Countries(name) VALUES('Džibutsko');
INSERT INTO Countries(name) VALUES('Dominika');
INSERT INTO Countries(name) VALUES('Dominikánská republika');
INSERT INTO Countries(name) VALUES('Východní Timor');
INSERT INTO Countries(name) VALUES('Ekvádor');
INSERT INTO Countries(name) VALUES('Egypt');
INSERT INTO Countries(name) VALUES('Salvador');
INSERT INTO Countries(name) VALUES('Rovníková Guinea');
INSERT INTO Countries(name) VALUES('Eritrea');
INSERT INTO Countries(name) VALUES('Estonsko');
INSERT INTO Countries(name) VALUES('Eswatini');
INSERT INTO Countries(name) VALUES('Etiopie');
INSERT INTO Countries(name) VALUES('Fidži');
INSERT INTO Countries(name) VALUES('Finsko');
INSERT INTO Countries(name) VALUES('Francie');
INSERT INTO Countries(name) VALUES('Gabon');
INSERT INTO Countries(name) VALUES('Gambie');
INSERT INTO Countries(name) VALUES('Gruzie');
INSERT INTO Countries(name) VALUES('Německo');
INSERT INTO Countries(name) VALUES('Ghana');
INSERT INTO Countries(name) VALUES('Řecko');
INSERT INTO Countries(name) VALUES('Grenada');
INSERT INTO Countries(name) VALUES('Guatemala');
INSERT INTO Countries(name) VALUES('Guinea');
INSERT INTO Countries(name) VALUES('Guinea-Bissau');
INSERT INTO Countries(name) VALUES('Guyana');
INSERT INTO Countries(name) VALUES('Haiti');
INSERT INTO Countries(name) VALUES('Honduras');
INSERT INTO Countries(name) VALUES('Maďarsko');
INSERT INTO Countries(name) VALUES('Island');
INSERT INTO Countries(name) VALUES('Indie');
INSERT INTO Countries(name) VALUES('Indonésie');
INSERT INTO Countries(name) VALUES('Írán');
INSERT INTO Countries(name) VALUES('Irák');
INSERT INTO Countries(name) VALUES('Irsko');
INSERT INTO Countries(name) VALUES('Izrael');
INSERT INTO Countries(name) VALUES('Itálie');
INSERT INTO Countries(name) VALUES('Pobřeží slonoviny');
INSERT INTO Countries(name) VALUES('Jamajka');
INSERT INTO Countries(name) VALUES('Japonsko');
INSERT INTO Countries(name) VALUES('Jordánsko');
INSERT INTO Countries(name) VALUES('Kazachstán');
INSERT INTO Countries(name) VALUES('Keňa');
INSERT INTO Countries(name) VALUES('Kiribati');
INSERT INTO Countries(name) VALUES('Kuvajt');
INSERT INTO Countries(name) VALUES('Kyrgyzstán');
INSERT INTO Countries(name) VALUES('Laos');
INSERT INTO Countries(name) VALUES('Lotyšsko');
INSERT INTO Countries(name) VALUES('Libanon');
INSERT INTO Countries(name) VALUES('Lesotho');
INSERT INTO Countries(name) VALUES('Libérie');
INSERT INTO Countries(name) VALUES('Libye');
INSERT INTO Countries(name) VALUES('Lichtenštejnsko');
INSERT INTO Countries(name) VALUES('Litva');
INSERT INTO Countries(name) VALUES('Lucembursko');
INSERT INTO Countries(name) VALUES('Madagaskar');
INSERT INTO Countries(name) VALUES('Malawi');
INSERT INTO Countries(name) VALUES('Malajsie');
INSERT INTO Countries(name) VALUES('Maledivy');
INSERT INTO Countries(name) VALUES('Mali');
INSERT INTO Countries(name) VALUES('Malta');
INSERT INTO Countries(name) VALUES('Marshallovy ostrovy');
INSERT INTO Countries(name) VALUES('Mauritánie');
INSERT INTO Countries(name) VALUES('Mauricius');
INSERT INTO Countries(name) VALUES('Mexiko');
INSERT INTO Countries(name) VALUES('Mikronésie');
INSERT INTO Countries(name) VALUES('Moldavsko');
INSERT INTO Countries(name) VALUES('Monako');
INSERT INTO Countries(name) VALUES('Mongolsko');
INSERT INTO Countries(name) VALUES('Černá Hora');
INSERT INTO Countries(name) VALUES('Maroko');
INSERT INTO Countries(name) VALUES('Mosambik');
INSERT INTO Countries(name) VALUES('Myanmar (Barma)');
INSERT INTO Countries(name) VALUES('Namibie');
INSERT INTO Countries(name) VALUES('Nepál');
INSERT INTO Countries(name) VALUES('Nizozemsko');
INSERT INTO Countries(name) VALUES('Nový Zéland');
INSERT INTO Countries(name) VALUES('Nikaragua');
INSERT INTO Countries(name) VALUES('Niger');
INSERT INTO Countries(name) VALUES('Nigérie');
INSERT INTO Countries(name) VALUES('Severní Makedonie');
INSERT INTO Countries(name) VALUES('Norsko');
INSERT INTO Countries(name) VALUES('Omán');
INSERT INTO Countries(name) VALUES('Pákistán');
INSERT INTO Countries(name) VALUES('Palau');
INSERT INTO Countries(name) VALUES('Palestina');
INSERT INTO Countries(name) VALUES('Panama');
INSERT INTO Countries(name) VALUES('Papua-Nová Guinea');
INSERT INTO Countries(name) VALUES('Paraguay');
INSERT INTO Countries(name) VALUES('Peru');
INSERT INTO Countries(name) VALUES('Filipíny');
INSERT INTO Countries(name) VALUES('Polsko');
INSERT INTO Countries(name) VALUES('Portugalsko');
INSERT INTO Countries(name) VALUES('Katar');
INSERT INTO Countries(name) VALUES('Rumunsko');
INSERT INTO Countries(name) VALUES('Rusko');
INSERT INTO Countries(name) VALUES('Rwanda');
INSERT INTO Countries(name) VALUES('Svatý Kryštof a Nevis');
INSERT INTO Countries(name) VALUES('Svatá Lucie');
INSERT INTO Countries(name) VALUES('Svatý Vincenc a Grenadiny');
INSERT INTO Countries(name) VALUES('Samoa');
INSERT INTO Countries(name) VALUES('San Marino');
INSERT INTO Countries(name) VALUES('Svatý Tomáš a Princův ostrov');
INSERT INTO Countries(name) VALUES('Saúdská Arábie');
INSERT INTO Countries(name) VALUES('Senegal');
INSERT INTO Countries(name) VALUES('Srbsko');
INSERT INTO Countries(name) VALUES('Seychely');
INSERT INTO Countries(name) VALUES('Sierra Leone');
INSERT INTO Countries(name) VALUES('Singapur');
INSERT INTO Countries(name) VALUES('Slovensko');
INSERT INTO Countries(name) VALUES('Slovinsko');
INSERT INTO Countries(name) VALUES('Šalomounovy ostrovy');
INSERT INTO Countries(name) VALUES('Somálsko');
INSERT INTO Countries(name) VALUES('Jihoafrická republika');
INSERT INTO Countries(name) VALUES('Jižní Korea');
INSERT INTO Countries(name) VALUES('Jižní Súdán');
INSERT INTO Countries(name) VALUES('Španělsko');
INSERT INTO Countries(name) VALUES('Srí Lanka');
INSERT INTO Countries(name) VALUES('Súdán');
INSERT INTO Countries(name) VALUES('Surinam');
INSERT INTO Countries(name) VALUES('Švédsko');
INSERT INTO Countries(name) VALUES('Švýcarsko');
INSERT INTO Countries(name) VALUES('Sýrie');
INSERT INTO Countries(name) VALUES('Tchaj-wan');
INSERT INTO Countries(name) VALUES('Tádžikistán');
INSERT INTO Countries(name) VALUES('Tanzanie');
INSERT INTO Countries(name) VALUES('Thajsko');
INSERT INTO Countries(name) VALUES('Togo');
INSERT INTO Countries(name) VALUES('Tonga');
INSERT INTO Countries(name) VALUES('Trinidad a Tobago');
INSERT INTO Countries(name) VALUES('Tunisko');
INSERT INTO Countries(name) VALUES('Turecko');
INSERT INTO Countries(name) VALUES('Turkmenistán');
INSERT INTO Countries(name) VALUES('Tuvalu');
INSERT INTO Countries(name) VALUES('Uganda');
INSERT INTO Countries(name) VALUES('Ukrajina');
INSERT INTO Countries(name) VALUES('Spojené arabské emiráty');
INSERT INTO Countries(name) VALUES('Velká Británie');
INSERT INTO Countries(name) VALUES('Spojené státy americké');
INSERT INTO Countries(name) VALUES('Uruguay');
INSERT INTO Countries(name) VALUES('Uzbekistán');
INSERT INTO Countries(name) VALUES('Vanuatu');
INSERT INTO Countries(name) VALUES('Vatikán');
INSERT INTO Countries(name) VALUES('Venezuela');
INSERT INTO Countries(name) VALUES('Vietnam');
INSERT INTO Countries(name) VALUES('Jemen');
INSERT INTO Countries(name) VALUES('Zambie');
INSERT INTO Countries(name) VALUES('Zimbabwe');

COMMIT;

